spring:
  application:
    name: api-gateway

server:
  port: 8080   # Gateway port

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/

        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/products/

        - id: cart-service
          uri: http://localhost:8083
          predicates:
            - Path=/cart/

        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=/orders/
