spring:
  application:
    name: cart-service

  datasource:
    url: jdbc:postgresql://localhost:5433/cart_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Actuator
  management:
    endpoints:
      web:
        exposure:
          include: "*"

  server:
    port: 8083